import type { Metadata } from "next";
import "./globals.css";
import { TChildren } from "@/lib/types/types";
import { poppins } from "@/lib/fonts";
import { ThemeProvider } from "./providers/ThemeProvider";
import AosProvider from "./providers/AosProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: TChildren) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AosProvider>{children}</AosProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
